### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by infinisil** [mobusoperandi/eelco#100]
Using a person's name as a project is not great, especially if the person is very well-known in the community already.

I already mentioned this [on Matrix](https://matrix.to/#/!avYyleMexqjFHoqrME:nixos.org/$RablF5pS0bDYzPJvIBnTLhH4UN8LiN7_BzoBDOxJvPU?via=nixos.org&via=matrix.org&via=nixos.dev), where @asymmetric, @fricklerhandwerk, @lf-, @stablejoy already indicated the same concern. Furthermore @proofconstruction and @danielsidhion also share this concern.

**Comment by philiptaron** [comment]
Here's a couple suggestions:

1. nix-example-tester
2. doctester.nix
3. does-it-run.nix
4. nix-example-vet

It doesn't have to be boring, either:

1. mighty-doctest (after your alias mightyiam)
2. doctest-buster (after the famous vet [Buster Lloyd-Jones](https://en.wikipedia.org/wiki/Buster_Lloyd-Jones))

**Comment by mightyiam** [comment]
Thank you for your concern and for feeling free to contact me about this.

As the readme states, naming this project eelco is in homage. That is, it's a payment of respect.

And it's also humorous.

And I like it. And I'm proud of it. I've always felt it is a great idea, filled with fondness and cuteness and silliness.

> Using a person's name as a project is not great, especially if the person is very well-known in the community already.

Sorry, I can't imagine a real problem here other than Eelco himself being offended. I would think most would be flattered.

> One might confuse eelco the project with Eelco the person

How about we try and see?

**Comment by proofconstruction** [comment]
I am less worried about the potential to offend than about the discoverability of the project when the name is overridden like this. Having to clarify — especially in search engines — that I'm talking about Eelco the person (and which one?) versus Eelco the library named after the person (... and which one?) is an extra step compared to just calling this something boring like `nixdotdev-codeblock-validator`. Besides, we want nix to eat the world, and nix.dev is its learning documentation, so this naming may incur trillions of hours of maintainer labor explaining over the rest of human existence.🙂

**Comment by stablejoy** [comment]
There is the exception of Linus and Linux but Linus himself used the name, he didn't need the person's approval. There is also the case of permanence of the project's name if the reputation of a living person degenerates in any way.

**Comment by asymmetric** [comment]
eelcode?

**Comment by lf-** [comment]
> eelcode?

eelcode is implying it is code that is strongly associated with eelco, which uhhhh i don't think is any better at all. certainly not descriptive of its purpose imo.

**Comment by mightyiam** [comment]
I still don't agree that anyone should bother suggesting — let alone asking — that this is renamed. I find that inappropriate. This must be [my karma](https://github.com/nix-community/dream2nix/issues/595).

For the record, if I were to agree, here's my suggestion: nixdoctest

**Comment by mightyiam** [comment]
Fine. I'll rename it. Thank @fricklerhandwerk for advising me to comply.

**Comment by infinisil** [comment]
Awesome thanks! Both nixdoctest or ndt sound good to me

**Comment by mightyiam** [comment]
Hey. Trying to reach a compromise, here. I still like the original name, eelco. Because I like the payment of respect and the humor involved. So, I had an idea. How about naming it dolstra? Eelco's username is eelco, so there would be less confusion. Please consider.

**Comment by furioncycle** [comment]
I think ndt is better than nixdoctest, I am not really sure the real implications of naming it eelco or even using some form of it.

**Comment by mightyiam** [comment]
Sorry, I'm done with this issue.

**Comment by networkException** [comment]
> Sorry, I'm done with this issue.

🤡
